# ---------- Build stage ----------
    FROM node:22-alpine AS build
    WORKDIR /app
    
    COPY package*.json ./
    RUN npm ci
    
    COPY . .
    ENV BUILD_OUT_DIR=dist
    RUN npm run build
    
    # ---------- Runtime stage ----------
    FROM nginx:alpine
    COPY --from=build /app/dist /usr/share/nginx/html
    EXPOSE 80
    CMD ["nginx", "-g", "daemon off;"]
    